---
- name: java installation
  hosts: all
  sudo: true
  user: root
  roles:
  - java


- name: newrelic monitoring
  hosts: all
  sudo: true
  user: root
  roles:
  - newrelic

  vars_files:
  - newrelic
